# Site settings
title: Camp for Coders 2015
description: 4 weeks of code at Rockhurst High School, Summer 2015
baseurl: "/CFC2015/"
url: "http://jameswclark.github.io"
highlighter: pygments

# Build settings
markdown: kramdown
